version: 0.2 

phases:
  build:
    commands:
      - echo Executing Build Phase
      - mvn clean package
  post_build:
    commands:
      - echo EBuild completed successfully
      
artifacts:
  files:
    - target/springboot.jar
  discard-paths: yes
    